# Generated by Django 4.2.8 on 2024-05-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='infill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='layers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='manufacturing_method',
            field=models.CharField(choices=[('3d_printing', '3D Printing'), ('cnc_machining', 'CNC Machining'), ('pcb_manufacturing', 'PCB Manufacturing')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='nozzle_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
