# Generated by Django 5.0.6 on 2024-05-26 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyer_app", "0002_fileupload_infill_fileupload_layers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="name",
        ),
        migrations.AddField(
            model_name="buyer",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
