# Generated by Django 5.0.6 on 2024-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyer_app", "0003_remove_buyer_email_remove_buyer_name_buyer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
